development:
  adapter: postgresql
  encoding: unicode
  database: grocerypad_development
  pool: 5
  username: postgres
  password: chung555
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: grocerypad_test
  pool: 5
  username: postgres
  password: chung555
  host: localhost